{% set version = "0.7.1" %}
{% set posix = 'm2-' if win else '' %}

package:
  name: r-mlr3proba
  version: {{ version|replace("-", "_") }}

source:
  url: https://mlr-org.r-universe.dev/src/contrib/mlr3proba_{{ version }}.tar.gz
  ## note these are not stable and get periodically rebuilt: see https://github.com/r-universe-org/help/discussions/262
  ## an official md5 checksum can be retrieved from: https://mlr-org.r-universe.dev/api/packages
  sha256: 33dfb556830138b5d1fb3319c411141e158202bd7a40302c51653e54b8c4f3fb

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ compiler('c') }}          # [not win]
    - {{ stdlib("c") }}            # [not win]
    - {{ compiler('m2w64_c') }}    # [win]
    - {{ stdlib("m2w64_c") }}      # [win]
    - {{ compiler('cxx') }}        # [not win]
    - {{ compiler('m2w64_cxx') }}  # [win]
    - {{ posix }}filesystem        # [win]
    - {{ posix }}make
    - {{ posix }}sed               # [win]
    - {{ posix }}coreutils         # [win]
    - {{ posix }}zip               # [win]
    - cross-r-base {{ r_base }}    # [build_platform != target_platform]
  host:
    - r-base
    - r-checkmate
    - r-data.table
    - r-distr6 >=1.8.4
    - r-ggplot2
    - r-mlr3 >=0.14.1
    - r-mlr3misc >=0.7.0
    - r-mlr3pipelines >=0.7.0
    - r-mlr3viz
    - r-paradox >=0.1.0
    - r-r6
    - r-rcpp >=1.0.4
    - r-survival
    - r-survivalmodels >=0.1.12
  run:
    - r-base
    - r-checkmate
    - r-data.table
    - r-distr6 >=1.8.4
    - r-ggplot2
    - r-mlr3 >=0.14.1
    - r-mlr3misc >=0.7.0
    - r-mlr3pipelines >=0.7.0
    - r-mlr3viz
    - r-paradox >=0.1.0
    - r-r6
    - r-rcpp >=1.0.4
    - r-survival
    - r-survivalmodels >=0.1.12

test:
  commands:
    - $R -e "library('mlr3proba')"           # [not win]
    - "\"%R%\" -e \"library('mlr3proba')\""  # [win]

about:
  home: https://mlr3proba.mlr-org.com
  dev_url: https://github.com/mlr-org/mlr3proba
  doc_url: https://mlr-org.r-universe.dev/mlr3proba
  license: LGPL-3.0-only
  summary: Provides extensions for probabilistic supervised learning for 'mlr3'.  This includes extending the regression task to probabilistic and interval regression, adding a survival task, and other specialized models, predictions, and measures. mlr3extralearners is available from <https://github.com/mlr-org/mlr3extralearners>.
  license_family: LGPL
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/LGPL-3

extra:
  recipe-maintainers:
    - conda-forge/r
    - pascal-git
